## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
#matrix:
#  allow_failures:
#  - julia: nightly

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Strs"); Pkg.test("Strs"; coverage=true)'
  - julia -e 'Pkg.clone("https://github.com/JuliaString/StrTables.jl.git"); Pkg.clone("https://github.com/JuliaString/LaTeX_Entities.jl.git"); Pkg.clone("https://github.com/JuliaString/Emoji_Entities.jl.git"); Pkg.clone("https://github.com/JuliaString/HTML_Entities.jl.git"); Pkg.clone("https://github.com/JuliaString/Unicode_Entities.jl.git"); Pkg.clone("https://github.com/JuliaString/Format.jl.git"); Pkg.clone(pwd()); Pkg.add("LightXML"); Pkg.add("JSON"); Pkg.build("LaTeX_Entities"); Pkg.build("Emoji_Entities"); Pkg.build("HTML_Entities"); Pkg.build("Unicode_Entities"); Pkg.test("Strs"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("Strs")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("Strs")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
