## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  allow_failures:
    - julia: nightly

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

## uncomment the following lines to override the default test script
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'VERSION < v"0.7.0-DEV" || (import Pkg) ; if VERSION < v"0.7.0-DEV.5183" ; l="_Entities"; for n in ("ModuleInterfaceTools", "StrTables", "LightXML", "JSON", "Format", "PCRE2", "InternedStrings", "StrAPI", "CharSetEncodings") ; Pkg.add(n) ; end ; t=("LaTeX","Emoji","HTML","Unicode"); for n in t; d=n*"_Entities" ; Pkg.add(d); Pkg.build(d) ; end; for n in ("ChrBase", "MurmurHash3", "StrBase", "StrRegex", "StrLiterals", "StrFormat", "StrEntities") ; Pkg.clone("https://github.com/JuliaString/$n.jl.git"); end ; Pkg.clone(pwd()); end ; Pkg.test("Strs"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'VERSION < v"0.7.0-DEV" || (using Pkg); cd(Pkg.dir("Strs")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'VERSION < v"0.7.0-DEV" || (using Pkg); cd(Pkg.dir("Strs")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
